db:
  image: postgres
  ports:
    - "5432"
redis:
  image: redis
  ports:
    - 6379
app:
  extends:
    file: common.yml
    service: railsimage
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes_from:
    - gems
  ports:
    - "3000:3000"
  links:
    - db
    - redis
sidekiq:
  extends:
    file: common.yml
    service: railsimage
  command: bundle exec sidekiq
  volumes_from:
    - gems
  links:
    - db
    - redis
gems:
  image: busybox
  volumes:
    - /ruby_gems/2.2